name: CI pipeline
run-name: Run CI pipeline

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v6

      - name: Make build directory
        run: mkdir -p build

      - name: Prep
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --target unit-tests

      - name: Test
        run: cd build && ctest --output-on-failure